### ISSUE TITLE
About computation of Elmo

### ISSUE THREAD

**Issue by bdhingra** [uwnlp/piqa#1]
Hi,

Thanks for uploading the code!

It seems that in [model.py](https://github.com/uwnlp/piqa/blob/master/model.py#L71) you are maintaining the scale and mixing parameters for computing the averaged Elmo representation. However, from my understanding of [`allennlp.modules.elmo.Elmo`](https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py#L34) this should be already taken care of by the `Elmo` class. 

Is there any reason for re-mixing the already mixed Elmo representations returned? Or am I misunderstanding something?

Thanks!
Bhuwan

**Comment by seominjoon** [comment]
You are right, and I was doing scaling twice... Thanks for pointing this out! https://github.com/uwnlp/piqa/commit/72c762390a09dfe04a17d165f80ba02322e9a2ec fixes the issue :)

**Comment by seominjoon** [comment]
FYI, this seems to improve the LSTM+SA+ELMo baseline non-trivially by 0.6% F1 (reaching 63.3%)
