### ISSUE TITLE
CUDA out of memory when using ELMo on a 12GB GPU

### ISSUE THREAD

**Issue by seominjoon** [uwnlp/piqa#2]
This did not happen previously, so I am currently investigating the issue.

**Comment by seominjoon** [comment]
Will need to use `--batch_size=32` for 12GB. For 24GB GPU, works well.
https://github.com/uwnlp/piqa/commit/f1b4520aa40233d24cbbcb13594bda2d49a8fded

**Comment by jhyuklee** [comment]
FYI, using ELMo with 12GB TitanXP (default batch_size = 64) works well :)
It takes up 9963MiB, and reaches 0.632 dev_f1 @ 5001.

**Comment by seominjoon** [comment]
Weird.. which commit version did you use btw?

**Comment by jhyuklee** [comment]
I'm working on the forked repo (https://github.com/jhyuklee/piqa),
and the latest commit is https://github.com/uwnlp/piqa/commit/7dfb6fe955db9cf1b0ef1825c3b15948629a4f86.

**Comment by bdhingra** [comment]
Worth pointing out that when I tried running the code on a 12GB GPU I also ran into a memory error with the default batch size of 64. Reducing the batch size to 32 solved the problem, and also gave a better F1 score of 63.5% (before applying the ELMO fix from https://github.com/uwnlp/piqa/commit/72c762390a09dfe04a17d165f80ba02322e9a2ec).

**Comment by seominjoon** [comment]
@bdhingra thanks, 32 surely seems to work better (I got 63.7%).

**Comment by jhyuklee** [comment]
After updating to https://github.com/uwnlp/piqa/commit/c6e871919a6c664d53db58fd2d7c047843ce2e75, batch_size=64 makes OOM for me, too.
